blog/urls.py
from django.urls import path
from .views import post_detail, post_list

app_name='blog'

urlpatterns = [
    path('', post_list, name='posts'),
    path('/<id>', post_detail, name='post_detail'),
]

portafolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from proyectos.views import inicio
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('blog', include('blog.urls')),

]


#Agregado para imagenes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyectos/urls.py
from django.urls import path

urlpatterns = [
    
]

blog/models.py
from django.db import models
import datetime

# Create your models here.
class Post(models.Model):
    titulo = models.CharField(max_length=200)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(datetime.date.today)
    imagen = models.ImageField(upload_to="blog/post/imagenes/", blank=True)

    def __str__(self):
        return self.titulo

proyectos/models.py
from django.db import models

# Create your models here.
class Proyecto(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to="proyectos/imagenes/")
    link = models.URLField(blank=True)

    def __str__(self):
        return self.titulo

blog/views.py
from django.shortcuts import render , get_object_or_404
from .models import Post

# Create your views here.
def post_list(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'post_detail.html',{'post': post})

proyectos/views.py
from django.shortcuts import render
from .models import Proyecto

# Create your views here.
def inicio(request):
    proyectos = Proyecto.objects.all()

    return render(request, 'inicio.html', {'proyectos': proyectos})

blog/templates/post_detail.html
{% extends 'base.html' %}


{% block contenido %}


<div class="text-center">
    <h2>{{post.titulo}} </h2>
    <h3 class="my-2 h4 text-muted">{{post.fecha|date:'d M Y'|upper}} </h3>

    <img src="{{post.imagen.url}} " alt="{{post.titulo}}" class="img-fluid">

    <div class="my-4">
        <p class="text-justify">{{post.cuerpo|safe}} </p>
    </div>
</div>



{% endblock %}

blog/templates/posts.html
{% extends 'base.html' %}


{% block contenido %}

<h1>Posts</h1>

{% for i in posts %}
<div class="p-3">
    <div class="card card-body bg-black card-post">
        <div class="row">
            <div class="col-3">
                <img src="{{i.imagen.url}} " alt="{{i.titulo}}" class="img-fluid">
            </div>
            <div class="col-9">
                <h2>{{i.titulo}} </h2>
                <p>{{i.cuerpo|striptags|truncatechars:100}} </p>
                <!-- truncatechars : Corta 100 caracteres  // striptags : no interpreta etiquetas html-->
                <p>{{i.fecha|date:'d M Y'|upper}} </p>


                <a href="{% url 'blog:post_detail' i.id %}" class="btn btn-primary">{{i.titulo}}</a>
            </div>
        </div>


    </div>
</div>
{% endfor %}

{% endblock contenido %}

proyectos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portafolio Felipe</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'estilos.css' %}">
</head>
<body class="text-light">
    
    {% include 'partials/navbar.html' %}
    
    <div class="container p-4">
        {% block contenido %}
        
        {% endblock contenido %}
    </div>
        
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

proyectos/templates/inicio.html
{% extends 'base.html' %}




{% block contenido %}

    {% load static %}

    <header class="row bg-black">
        <div class="col-md-4">
            <img src="{% static 'cv/felipe.png' %}" alt="" width="400px">
        </div>
        <div class="col md-8 my-auto">
            <h1>Yo soy <strong>Felipe Bastidas</strong></h1>
            <h3>Soy Ingeniero Civil en Informatica </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione voluptatum, est quos nesciunt magnam eos, nostrum animi tempore esse praesentium ut nemo labore quisquam rem maxime odit vero minima deserunt cupiditate excepturi ipsam porro nisi tempora! Dolor beatae dolorum iure consequuntur sit doloremque, odit quo architecto quas voluptatum reiciendis consectetur ratione ad temporibus adipisci facere esse! Sunt, perspiciatis. Obcaecati voluptas ad debitis explicabo dolorum consectetur iste est, nihil numquam illo eligendi cum quos, libero a atque iusto? Totam, fugit neque aperiam asperiores voluptatibus facere ab repellat vero, sequi obcaecati dignissimos blanditiis. Beatae porro id ex. Illum reprehenderit tempore fugiat facere?</p>
            <a href="{% static 'cv/cv.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Descargar CV</a>
        </div>
    </header>

    <div class="row my-4 text-center">
        <h3>Mis Proyectos</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illo, non!</p>

            {% for i in proyectos %}
                
                <div class="col-md-4 p-4">
                    <div class="card bg-black card-project">
                        <img class="card-img-top" src="{{i.imagen.url}} " alt="{{i.titulo}}" height="300px"/>
                        <div class="card-body">
                            <h2>{{i.titulo}} </h2>
                            <p>{{i.descripcion}} </p>

                                {% if i.link %}
                                    <a href="{{i.link}}" class="btn btn-light rounded-0 btn-sm" target="_blank">Ver Codigo</a>
                                {% endif %}
                                
                        </div>
                    </div>
                </div>
            
            {% endfor %}
    </div>

{% endblock contenido %}
    

proyectos/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">FF</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'cv/cv.pdf' %}" target="_blank">Descargar Curriculum</a>
          </li>
          
        </ul>
        
      </div>
    </div>
  </nav>